### ISSUE TITLE
Homebrew Subclass: Druid Circle of the Guardian

### ISSUE THREAD

**Issue by staticburst** [TheGiddyLimit/homebrew#1184]
I'm no coder but I thought I'd contribute just for fun! This is a subclass in my home game, created by a friend of mine! Basically, if a Druid had the equivalent of a bladesinger subclass.  Let me know if I did anything wrong, because I like learning new stuff.

https://github.com/staticburst/Staticburst5eHomebrew/blob/main/Spicy%20Spook%3B%20Circle%20of%20the%20Guardian

**Comment by Git-GoR** [comment]
Homebrew files additions are usually done through a Pull Request rather than an Issue, as it's easier to merge. You can read about it [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), although I think Github will show you a shortcut in the repo's main page if it detects you have a fork with changes.

As for issues with the file, at lvl 2 you are referencing the feature `Verdant Warrior`, which does not exist,  instead of `Blessings of Strength`.

There are also a couple of `{@` tags you could add, but that's extra functionality and does not break the file.

**Comment by staticburst** [comment]
Ah, I'll have to figure that part out, just a dabbler at the moment.  I was just following the prompt on the homebrew folder page:

> Contributions are welcome. For the GitHub-literate, make a pull request.* For everyone else, create an Issue and post a link to your file (PasteBin is fine), and I (or other maintainers, in future) can add it for you.

Thanks for the catch on the missed reference! That has been amended.

**Comment by revilowaldow** [comment]
Closed by #1197
